# Generated by Django 2.1.7 on 2019-05-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
    ]
