# Generated by Django 2.1.7 on 2019-05-29 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190506_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.IntegerField(default=100000, validators=[django.core.validators.MinValueValidator(100000)]),
        ),
    ]
