# Generated by Django 2.1.7 on 2019-05-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('portfolio_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClubRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Club')),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WitsSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='WitsSportExecutive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Portfolio')),
            ],
        ),
    ]
